#!/bin/bash
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
package main

import "net"

func main() {
    ln, _ := net.Listen("tcp", ":8080")
    for {
        conn, _ := ln.Accept()
        go handleConnection(conn)
    }
}

func handleConnection(conn net.Conn) {
    // Handle network traffic
}
